# docker-compose.yml
version: '3'
services:
  python_service:
    build:
      context: .
      dockerfile: dockerfile.python
      args:
        - BASE_IMAGE=python:3.12.5
        - APP_VERSION=12.0
    environment:
      - DEBUG=true
    image: adegokebabatunde/python_web:3.12.5

  node_service:
    build:
      context: .
      dockerfile: dockerfile.node
      args:
        - BASE_IMAGE=node:20.17.0
        - APP_NAME=my-nodejs-app
    environment:
      - NODE_ENV=development
    image: adegokebabatunde/node_web:20.17.0
