# version: '3'
# services:
#   nginx_service:
#     build:
#       context: .
#       dockerfile: dockerfile.nginx
#       args:
#         - BASE_NGINX=nginx:latest
#       labels:
#         - NGINX_VERSION=version:1.0.0
#         - NGINX_NAME=maintainer:adegoke
#       image: adegokebabatunde/nginx:1.0.0

#       ports:
#         - "80:80"

version: '3'

services:
  nginx_service:
    build:
      context: .
      dockerfile: dockerfile.nginx
      args:
        - BASE_NGINX=nginx:latest
     

    image: adegokebabatunde/nginx:1.0.0

    ports:
      - "80:80"

      